apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-storage
  namespace: CHANGE-ME
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: vsphere-sc
